# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    ports:
      - 3806:3306
    environment:
      MARIADB_ROOT_PASSWORD: root

  adminer:
    image: adminer
    environment:
      ADMINER_DESIGN: dracula
    restart: always
    ports:
      - 8080:8080